services:
  - docker

dist: focal

env:
  global:
    - TZ=UTC # timezone importante, altrimenti cambierebbe in base al luogo in cui mi trovo
    - IMAGE_NAME="matteocaval/docker-test"

before_script:
  - export TAG="$(git describe || git log -n1 --date=format:'%Y-%m-%dT%H%M%S' --format=%cd)$(date +%Y-%m-%d_%H%M)"

script:
  - docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$TAG . # genero con il doppio nome
  # Login into docker hub from a non-interactive terminal
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin docker.io
  # Push the images, with both names (upload will happen only once, as they refer the same layer)
  - docker push $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME:latest